version: '2.1'

services:
  webgoat:
    image: vargadan/webgoat-8.0:8.0
    user: webgoat
    environment:
      - WEBWOLF_HOST=localhost
      - WEBWOLF_PORT=9090
      - spring.datasource.url=jdbc:postgresql://localhost:5432/webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
      - webgoat.server.directory=/home/webgoat/.webgoat/
      - webgoat.user.directory=/home/webgoat/.webgoat/
    ports:
      - "8080:8080"
      - "9001:9001"
  webwolf:
    image: vargadan/webwolf-8.0:8.0
    environment:
      - WEBWOLF_HOST=localhost
      - WEBWOLF_PORT=9090    
      - spring.datasource.url=jdbc:postgresql://localhost:5432/webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
    ports:
      - "9090:9090"
  webgoat_db:
    image: postgres:9.4
# Uncomment to store the state of the database on the host.
#    volumes:
#      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=webgoat
      - POSTGRES_USER=webgoat
      - POSTGRES_DB=webgoat
    ports:
      - "5432:5432"

