version: '2.1'

services:
  webgoat:
    image: webgoat/webgoat-8.0
    user: webgoat
    environment:
      - WEBWOLF_HOST=sprg-owasp.el.eee.intern
      - WEBWOLF_PORT=9090
      - WEBGOAT_HOST=sprg-owasp.el.eee.intern
      - WEBGOAT_PORT=8080
      - spring.datasource.url=jdbc:postgresql://sprg-owasp.el.eee.intern:5432/webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
      - webgoat.server.directory=/root/webgoat/
      - webgoat.user.directory=/root/webgoat/
    ports:
      - "8080:8080"
  webwolf:
    image: webgoat/webwolf
    environment:
      - WEBWOLF_HOST=sprg-owasp.el.eee.intern
      - WEBWOLF_PORT=9090
      - WEBGOAT_HOST=sprg-owasp.el.eee.intern
      - WEBGOAT_PORT=8080
      - spring.datasource.url=jdbc:postgresql://sprg-owasp.el.eee.intern:5432/webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
    ports:
      - "9090:9090"
  webgoat_db:
    image: postgres:9.4
    volumes:
      - /root/webgoat_db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=webgoat
      - POSTGRES_USER=webgoat
      - POSTGRES_DB=webgoat
    ports:
      - "5432:5432"
